// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Nokia Rest api
Nokia Rest api


    Schemes:
      http
    Host: localhost
    BasePath: /v1/rest
    Version: 1.0
    Contact: Shivang Goswami<shivang.goswami@outlook.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
