// Code generated by go-swagger; DO NOT EDIT.

package nokiaapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteDeleteHandlerFunc turns a function with the right signature into a delete delete handler
type DeleteDeleteHandlerFunc func(DeleteDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDeleteHandlerFunc) Handle(params DeleteDeleteParams) middleware.Responder {
	return fn(params)
}

// DeleteDeleteHandler interface for that can handle valid delete delete params
type DeleteDeleteHandler interface {
	Handle(DeleteDeleteParams) middleware.Responder
}

// NewDeleteDelete creates a new http.Handler for the delete delete operation
func NewDeleteDelete(ctx *middleware.Context, handler DeleteDeleteHandler) *DeleteDelete {
	return &DeleteDelete{Context: ctx, Handler: handler}
}

/*DeleteDelete swagger:route DELETE /delete nokiaapi deleteDelete

Delete Data

Delete data

*/
type DeleteDelete struct {
	Context *middleware.Context
	Handler DeleteDeleteHandler
}

func (o *DeleteDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
