// Code generated by go-swagger; DO NOT EDIT.

package nokiaapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "nokia/models"
)

// DeleteDeleteOKCode is the HTTP code returned for type DeleteDeleteOK
const DeleteDeleteOKCode int = 200

/*DeleteDeleteOK status

swagger:response deleteDeleteOK
*/
type DeleteDeleteOK struct {

	/*
	  In: Body
	*/
	Payload *models.Status `json:"body,omitempty"`
}

// NewDeleteDeleteOK creates DeleteDeleteOK with default headers values
func NewDeleteDeleteOK() *DeleteDeleteOK {

	return &DeleteDeleteOK{}
}

// WithPayload adds the payload to the delete delete o k response
func (o *DeleteDeleteOK) WithPayload(payload *models.Status) *DeleteDeleteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete delete o k response
func (o *DeleteDeleteOK) SetPayload(payload *models.Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteDeleteDefault Generic error response

swagger:response deleteDeleteDefault
*/
type DeleteDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteDeleteDefault creates DeleteDeleteDefault with default headers values
func NewDeleteDeleteDefault(code int) *DeleteDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete delete default response
func (o *DeleteDeleteDefault) WithStatusCode(code int) *DeleteDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete delete default response
func (o *DeleteDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete delete default response
func (o *DeleteDeleteDefault) WithPayload(payload *models.Error) *DeleteDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete delete default response
func (o *DeleteDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
